### ISSUE TITLE
I can't download it as a flac file

### ISSUE THREAD

**Issue by meikoucho** [mmig/speech-to-flac#7]
I can't download it as a flac file, and the demo site has the same problem.

**Comment by russaa** [comment]
Could you give some more details, e.g. which browser did you use?

I just tested the demo site again with the latest Chrome (v94.x) and FireFox (v89.x), and it did work for me.

A common pitfall could be, that the browser asks for some permission, and it is overlooked, or already disabled:  
this demo needs permission to use the microphone, and the browser may also ask permission to for downloading the recorded audio file (since the download is triggered programmatically, and not directly by the user).

If you still have problems, it could also help to look into the JavaScript console (web developer tools of the browser), if there are some warnings or error messages there.

**Comment by meikoucho** [comment]
Thanks, I updated chrome and now I can download it!
